### ISSUE TITLE
1.12 release work

### ISSUE THREAD

**Issue by gvorbeck** [gvorbeck/codex-quest#75]
- [x] Add Necromancer Class #32 
- [x] Migrate to Vite #72 
    - [x] Update README to reflect new tech stack
    - [x] Fix broken images
- [x] Turn the Undead for Clerics #67 
    - [x] if class has `powers` and the power is category "weapons" show in weapons section of equipment.
    - [x] Cleric Turn Undead power
- [x] Spellbooks auto given to relevant classes #61 
- [x] Holy Symbols auto given to Clerics/etc
- [x] Update Footer version # to 1.12.0.0
- [x]  Refactor EquipmentList to remove repeated code
- [x] Add site email/pass login

**Comment by gvorbeck** [comment]
Anticipated problem to watch for at launch: images may start breaking due to how the paths created by CRA were embedded in the DB values. Vite created paths will be different. 

Moving npm>yarn to 1.13 as it's being problematic.
